Add optional gear packages from Cairn
Ashmogh/morii-vtt pull request #87
Opened 2023-01-30 20:42 UTC by ptaranat

Fixes #83

2023-01-31 15:36 UTC, Ashmogh commented
Looks good, although I've noticed a flaw in my approach, see #83. Other than that on line 9 in `WEAPONS.ts`, the resulting object should have `damage: damage`. As for the unknowns:
- Detect sounds pretty vague, I think we should just put Detect Magic there
- Not sure about this, the thing is, the way it works now, client gets the CAIRN data only on fresh startup of game (on refresh basically). So if we generate the Charm/Detect choice on server then I believe the choice will be made for the first character generated and then it repeats for every other character. But I also don't see a clean way to move the choice to client for now (maybe other than adding new item type 'choice', that we would have to convert on client during character creation), so I would just leave it like it is for now.
- Companions are tricky, will look at it little bit more, as we have the screen space to create UI for this, but the data structure will have to be somewhat special. Would leave it as a weapon item for now.
- Yochai mentioned that it was an error, and that it is up to the table to decide whether longbow does d8 or d6 damage. Would create custom Rangers Longbow (d8) that differs from the SRD Bow (d6), like you did.
- I liked the proposed #91, i.e. deal with it on client, and leave it as a general item on server.

2023-01-31 16:27 UTC, ptaranat commented
For Charm or Detect, I will create a Spellbook (Charm or Detect) and in its description contain both spells. I will leave a note to instruct the user to edit the item accordingly.

Let’s keep companions as GM NPCs for now. Perhaps we can let GM give NPCs to PCs in the future.

I will rename the rangers d8 longbow to Warbow. Historically, these were the heaviest longbows used in Europe. It also adds some flavor to a Ranger who was may have formerly been a veteran.

2023-02-02 03:03 UTC, Ashmogh requested changes
Functions `createItem`, `getRandomSpellbook` and `getCharmOrDetectSpellbook` are fine. 

I would use the class structure for `WEAPONS` in the same way armor works now, like #89.
Also, if we change the structure for weapons, the function [`getRandomWeapon`](https://github.com/Ashmogh/morii-vtt/blob/bb83a552886e7a4b4354f1940f603a4afe58f0f7/src/client/src/components/Game/CharacterSheet/Cairn/CreateRandomSheetCairn.svelte#L116) has to simplified to look similar to how `getRandomArmor` looks now.  

`Gauntlets` in `ARMOR` can be deleted as you were right, they should be a custom item. 

For  `GEAR_PACKAGES` I would change the structure to `{ name: string, items: ItemCairn[]}[]`, see `MOCK_GEAR` in #96, as Svelecte doesn't play nicely with Records.

SRD items can be added same way it's done here, and e.g. `new ArmorCairn({ name: 'Shield', armor: '+1' }).getItem()` can be used for custom weapons/armor. 

We might want to flip the approach in the classes to use getRecord instead of getItem in the future, but for now this should work sufficiently.

2023-02-02 03:22 UTC, ptaranat commented
Thanks for the feedback. I'll take a look when I get the chance unless it is blocking something.

- I'll adjust the class structure for WEAPONS to be like ARMORS, along with accompanying functions
- Remove Gauntlets from ARMORS
- Change GEAR_PACKAGES structure to not use Records

2023-02-10 20:53 UTC, Ashmogh approved these changes
Looks good!

2023-02-10 20:55 UTC, merged